<?php
/** @var \Tan\EnhancedEcommerce\ViewModel\UserBaseInformation $baseUserInfo */
$baseUserInfo = $block->getUserViewModel();

//info('base');
//info($baseUserInfo->getData());

/** @var \Tan\EnhancedEcommerce\ViewModel\UserCouponInformation $couponUserInfo */
$couponUserInfo = $block->getUserCouponViewModel();

//info('coupon');
//info($couponUserInfo->getData());

/** @var \Tan\EnhancedEcommerce\ViewModel\UserRewardInformation $rewardUserInfo */
$rewardUserInfo = $block->getUserRewardViewModel();

//info('reward');
//info($rewardUserInfo->getData());

/** @var \Tan\EnhancedEcommerce\ViewModel\UserSubscribeInformation $subscribeUserInfo */
$subscribeUserInfo = $block->getUserSubscribeViewModel();

//info('subscriber');
//info($subscribeUserInfo->getData());

?>

